exports.BUDGET_STATUS = {
  Cancelled: -1,
  Discontinued: 0,
  Pending: 1,
  "HOD Approved": 2,
  "In Progress": 3,
  "Finance Approved": 4,
  Completed: 5,
};

exports.CLAIM_STATUS = {
  Saved: -2,
  Cancelled: -1,
  Autogenerated: 0, // 'Claimant To Approve'
  Pending: 1, // 'HOD To Approve'
  "HOD Approved": 2, // 'Finance To Ack.'
  "In Progress": 3, // 'Finance To Approve'
  "Finance Approved": 4, // 'Finance To Complete'
  Completed: 5, // 'Finance To Recon'
  Reconciled: 6,
};

exports.CC_STATUS = {
  Cancelled: 0,
  "Pending tag": 1, // Finance To Tag
  "Pending document": 2, // Pending PIC to upload a document
  "Pending review": 3, // Pending Finance to review document
  Reconciled: 4,
};

exports.WC_STATUS = {
  // note: active and pending are for subscriptions
  ACTIVE: "active",
  COMPLETED: "completed",
  PENDING: "pending",
  PROCESSING: "processing",
  REFUNDED: "refunded",
  FAILED: "failed",
  ON_HOLD: "on-hold",
  CANCELLED: "cancelled",
};

exports.SHIPMENT_STATUS = {
  PENDING: "Pending",
  RECEIVED: "Received",
  LOST: "Lost",
  DELAYED_RECEIVE: "Delayed Received",
  OTHER: "Other",
};
